# Site settings
title: Prompt Engineering Blog
description: >-
  A community-focused blog on AI prompt engineering techniques, best practices,
  and the latest research to help you get the most out of large language models.
baseurl: "/PromptBlog" # the subpath of your site, e.g. /blog
url: "https://katinka-ux.github.io" # the base hostname & protocol for your site

# Don't use any theme - we have custom layouts
theme: null

# Author information
author:
  name: Prompt Engineering Team
  email: example@promptengineering.blog

# Social media
social:
  github: https://github.com/katinka-ux
  twitter: https://twitter.com/yourusername
  linkedin: https://linkedin.com/in/yourusername

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# Pagination
paginate: 6
paginate_path: "/page/:num/"

# Collections
collections:
  drafts:
    output: true
    permalink: /:collection/:name

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
  - scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"
      comments: false
  - scope:
      path: ""
    values:
      layout: "default"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github
  - CHANGELOG.md
  - README.md
  - LICENSE
  - server.py
  - replit.nix
  - PersonalPromptBlog.zip